name: string_manager
description: a flutter package for managing app strings in dart/flutter particularly internationalization.
version: 0.0.1
homepage: https://github.com/folaoluwafemi/string_manager

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  hive: ^2.2.1
  intl: ^0.17.0
  translator: ^0.1.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  mockito: ^5.2.0

