name: string_manager
description: a flutter package for managing app strings in dart/flutter particularly internationalization.
version: 0.0.1
homepage: https://github.com/folaoluwafemi/string_manager

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.2.0

flutter:
